// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx2EoomA42uZ-G6S6xli1Rn_OtUEbp4eY',
    appId: '1:642585158933:web:9ac58d5d7bd7da50bfb51c',
    messagingSenderId: '642585158933',
    projectId: 'ecosphere-explorer',
    authDomain: 'ecosphere-explorer.firebaseapp.com',
    storageBucket: 'ecosphere-explorer.appspot.com',
    measurementId: 'G-LJR8WJTVX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQdu8WbbKvc71N1Bn2tPWR-EX5Flp7kl8',
    appId: '1:642585158933:android:de93eb47d7516f28bfb51c',
    messagingSenderId: '642585158933',
    projectId: 'ecosphere-explorer',
    storageBucket: 'ecosphere-explorer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5V7K6pfQ8NWL4t4NYRVHf1mU80_xsMHQ',
    appId: '1:642585158933:ios:83f0153541679209bfb51c',
    messagingSenderId: '642585158933',
    projectId: 'ecosphere-explorer',
    storageBucket: 'ecosphere-explorer.appspot.com',
    iosBundleId: 'com.example.msuHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5V7K6pfQ8NWL4t4NYRVHf1mU80_xsMHQ',
    appId: '1:642585158933:ios:9e163f7fc569eccdbfb51c',
    messagingSenderId: '642585158933',
    projectId: 'ecosphere-explorer',
    storageBucket: 'ecosphere-explorer.appspot.com',
    iosBundleId: 'com.example.msuHackathon.RunnerTests',
  );
}
